#@TYPE: Machine
#@NAME: Hammerhead Sensor Module machine configuration
#@DESCRIPTION: Machine configuration for the Hammerhead Sensor Module - extended from the raspberrypi5 machine

require conf/machine/raspberrypi5.conf

MACHINE_EXTRA_RRECOMMENDS:remove = " \
    bluez-firmware-rpidistro-bcm4345c0-hcd \
    bluez-firmware-rpidistro-bcm4345c5-hcd \
    "

# Choose rpi linux fork with hammerhead sources
PREFERRED_PROVIDER_virtual/kernel ??= "linux-hammerhead"

# Use hammerhead device tree
RPI_KERNEL_DEVICETREE = "broadcom/hammerhead.dtb"

# Use hammerhead defconfig
KBUILD_DEFCONFIG:hammerhead ?= "hammerhead_defconfig"

# Expose console on UART0, gpio pins 14/15
SERIAL_CONSOLES = "115200;ttyAMA0"

# Remove quiet from kernel command line to see early boot messages
CMDLINE:remove = "quiet"

# Enable UART serial console on pins 14/15 and disable bluetooth
RPI_EXTRA_CONFIG += "\nenable_uart=1\n"
RPI_EXTRA_CONFIG += "\ndtoverlay=uart0\n"
RPI_EXTRA_CONFIG += "\ndtoverlay=disable-bt\n"
RPI_EXTRA_CONFIG += "\nenable_rp1_uart=1\n"
RPI_EXTRA_CONFIG += "\nuart_2ndstage=1\n"
# Load hammerhead device tree
RPI_EXTRA_CONFIG += "\ndevice_tree=hammerhead.dtb\n"

# We don't want bluetooth
MACHINE_FEATURES:remove = "bluetooth keyboard"
COMBINED_FEATURES:remove = "bluetooth"
